Document supported version is stable-3.3
Documentation states this plugin works on 3.2, but actually it breaks
when built on 3.2 with:

error: cannot find symbol
 private PluginConfig.Update pluginConfig;

error: cannot find symbol
import com.google.gerrit.acceptance.WaitUtil;

Given that stable-3.2 is going to be EOL very soon, update documentation
to state that support is only from stable-3.3

Change-Id: I1648888f23d4cbff6ab87c7bb77020fc96c99b4c