Introduce projectVersion cache
Introduces a caching mechanism to reduce the number of requests to
DynamoDB by storing the current life version of a project.

Cherry-picked from bae28b0cca4900dacbedce70c745df8834633222.
Adapted DynamoDBRefDatabaseIT test to avoid compilation error:

cannot infer type arguments for TypeLiteral<T>
'<>' with anonymous inner classes is not supported in -source 8

Change-Id: Ia260b0c7a684b3314bd32562eb0602fd4d54a20e